#theme: minima
theme: jekyll-theme-slate
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      language: ua
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      language: ua

url: "https://navpil.github.io"
plugins:
  - jekyll-sitemap